[package]
name = "application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
domain = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
storage-db = { workspace = true }
broker-connector = { path = "../../adapters/broker-connector" }
dukascopy-rs = { path = "../../scrapers/dukascopy-rs" }
publisher-traderfamily = { workspace = true }
rstest = { workspace = true }
