[package]
name = "dukascopy-rs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
domain = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
byteorder = { workspace = true }
lzma-rs = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
