use axum::Json;
use serde::Serialize;

#[derive(Serialize)]
pub struct StrategyDto {
    pub id: &'static str,
    pub name: &'static str,
    pub code: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub author: &'static str,
    pub win_rate_pct: f64,
    pub profit_factor: f64,
    pub recovery_factor: f64,
    pub sharpe_ratio: f64,
    pub sortino_ratio: f64,
    pub calmar_ratio: f64,
    pub wfer_pct: f64,
    pub is_tf_compliant: bool,
    pub supported_symbols: Vec<&'static str>,
    pub is_specialist: bool,
    pub specialist_label: Option<&'static str>,
}

pub async fn strategies_handler() -> Json<Vec<StrategyDto>> {
    let list = vec![
        StrategyDto {
            id: "pola-n-core",
            name: "TF Pola N Production (v1 Baseline)",
            code: "STRAT_POLA_N_V1",
            description: "Strategi fraktal multi-dekade berbasis konfirmasi swing L1-H1-L2 dan retest Golden Zone 50.0% - 61.8%.",
            category: "MARKET_STRUCTURE",
            author: "TF Quantitative Lab",
            win_rate_pct: 29.5,
            profit_factor: 1.81,
            recovery_factor: 11.55,
            sharpe_ratio: 2.14,
            sortino_ratio: 3.42,
            calmar_ratio: 4.12,
            wfer_pct: 94.8,
            is_tf_compliant: true,
            supported_symbols: vec![
                "XAUUSD", "EURUSD", "GBPUSD", "USDCHF", "AUDUSD", "NZDUSD", "EURGBP", "USDJPY",
            ],
            is_specialist: false,
            specialist_label: None,
        },
        StrategyDto {
            id: "pola-n-v2",
            name: "TF Pola N Adaptive (v2 Gold Specialist)",
            code: "STRAT_POLA_N_V2_GOLD",
            description: "Model kuantitatif fraktal Pola N khusus Emas (XAUUSD) dengan Fibonacci Golden Pocket 61.8%, Session Liquidity Filter (10-21 UTC), dan Target R:R 1:1.08 (Master/Legend Tier 80% Revenue Share).",
            category: "GOLD_SPECIALIST",
            author: "TF Quantitative Lab",
            win_rate_pct: 34.8,
            profit_factor: 2.19,
            recovery_factor: 15.82,
            sharpe_ratio: 3.10,
            sortino_ratio: 4.60,
            calmar_ratio: 6.20,
            wfer_pct: 98.2,
            is_tf_compliant: true,
            supported_symbols: vec!["XAUUSD"],
            is_specialist: true,
            specialist_label: Some("⭐ GOLD SPECIALIST (LEGEND PF 2.19)"),
        },
        StrategyDto {
            id: "dual-ema-trend",
            name: "TF Dual EMA Dynamic Trend",
            code: "STRAT_EMA_TREND_V2",
            description: "Sistem pengikut tren dinamis EMA 20 & 50 dengan filter slope momentum dan konfirmasi volume interbank.",
            category: "TREND_FOLLOWING",
            author: "TF Quantitative Lab",
            win_rate_pct: 34.2,
            profit_factor: 1.62,
            recovery_factor: 5.12,
            sharpe_ratio: 1.84,
            sortino_ratio: 2.91,
            calmar_ratio: 3.45,
            wfer_pct: 88.6,
            is_tf_compliant: true,
            supported_symbols: vec![
                "EURUSD", "GBPUSD", "USDCHF", "AUDUSD", "NZDUSD", "EURGBP", "USDJPY", "XAUUSD",
            ],
            is_specialist: false,
            specialist_label: None,
        },
        StrategyDto {
            id: "liquidity-order-block",
            name: "TF Smart Money Liquidity Engine",
            code: "STRAT_SMC_OB_V1",
            description: "Deteksi manipulasi likuiditas institusional (Liquidity Sweep & Fair Value Gap Mitigation).",
            category: "SMART_MONEY",
            author: "TF Quantitative Lab",
            win_rate_pct: 35.1,
            profit_factor: 1.88,
            recovery_factor: 6.45,
            sharpe_ratio: 2.05,
            sortino_ratio: 3.10,
            calmar_ratio: 3.95,
            wfer_pct: 91.2,
            is_tf_compliant: true,
            supported_symbols: vec![
                "EURUSD", "GBPUSD", "USDCHF", "AUDUSD", "NZDUSD", "EURGBP", "USDJPY", "XAUUSD",
            ],
            is_specialist: false,
            specialist_label: None,
        },
    ];

    Json(list)
}
