[package]
name = "domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
toml = { workspace = true }


[dev-dependencies]
tokio = { workspace = true }
rstest = { workspace = true }
proptest = { workspace = true }
mockall = { workspace = true }
